# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: dlist-custom
version: '0.0.0'
github: "lierdakil/dlist-template"
license: MIT
author: "Nikolay Yakimov"
maintainer: "Nikolay Yakimov"

extra-source-files:
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  source-dirs: library

benchmarks:
  dlist-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - dlist-custom
    - criterion
    - deepseq
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts "-N -H1G -M2G"

tests:
  dlist-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - dlist-custom
    - tasty
    - tasty-quickcheck
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
